"""remove description from froduct model

Revision ID: 4979484c07f6
Revises: a602d3089c43
Create Date: 2024-04-03 15:32:50.869906

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4979484c07f6"
down_revision: Union[str, None] = "a602d3089c43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "description", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
