"""add slug field to products table

Revision ID: a602d3089c43
Revises: e77ab115372d
Create Date: 2024-04-02 15:36:16.834539

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a602d3089c43"
down_revision: Union[str, None] = "e77ab115372d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("slug", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "slug")
    # ### end Alembic commands ###
