"""make slug column in products table type text

Revision ID: d244f95808ef
Revises: a9050f34135f
Create Date: 2024-04-03 17:51:01.529425

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d244f95808ef"
down_revision: Union[str, None] = "a9050f34135f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "slug",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "slug",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "products",
        "name",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
